
vec3f Nrefr = N; 
float NdotD = dot(normal, ray.dir)
float etai = 1, etat = ior; // etai is the index of refraction of the medium the ray is in before entering the second medium 
if (NdotD < 0) { 
    // Outside the surface, cos(theta) should be positive
    NdotI = -NdotI; 
} 
else { 
    // Outside the surface, cos(theta) is already positive but reverse normal direction
    Nrefr = -N; 
    // swap the refraction indices
    swap(etai, etat); 
} 
float eta = etai / etat; // n_1 / n_2 